### PR TITLE
Fixed redirection after advertisement site

### PR DESCRIPTION
**Pull request by JackBailey**
It would redirect to the advertisement site fine but after it would redirect to the system home, this worked for me and should work perfectly for everyone else.
You may need to change line 54 (starting return '//' . $_SERVER['SERVER_NAME'] ) as the comment says if yourls is not installed in your base domain

### CODE REVIEW

**Comment by JackBailey** [comment]
There may be a few inefficiencies with the code as I haven't written in php or have much experience with making a yourls plugin but it works and I've commented what the lines I added do so you're welcome to fix them

**Comment by 8MiYile** [comment]
Hi brother, my repository references your updates and supports git updates
Thanks
https://github.com/8Mi-Tech/yourls-conditional-urlads

**Comment by JackBailey** [comment]
> Hi brother, my repository references your updates and supports git updates
> Thanks
> https://github.com/8Mi-Tech/yourls-conditional-urlads

Looks great, thanks. Might be worth submitting a PR to the plugin list for yourls if you haven't already

**Comment by 8MiYile** [comment]
> 



> > Hi brother, my repository references your updates and supports git updates
> > Thanks
> > https://github.com/8Mi-Tech/yourls-conditional-urlads
> 
> Looks great, thanks. Might be worth submitting a PR to the plugin list for yourls if you haven't already

https://github.com/YOURLS/awesome-yourls/pull/132

**Comment by 8MiYile** [comment]
@JackBailey you can check out my update log
https://github.com/8Mi-Tech/yourls-conditional-urlads/issues/1

**Comment by HeroCC** [comment]
sorry I didn't see this until now, merging -- thanks for the contribution!

**Comment by HeroCC** [comment]
Fixes #3

**Pull request merged**
